name: brasilia
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # c
  cupertino_icons: ^1.0.2

  # f
  flutter_color: ^2.0.0
  flutter_colorpicker: ^1.0.3
  flutter_svg: ^1.0.3

  # g
  get: ^4.6.1

  # r
  responsive_builder: ^0.4.2

  # u
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
    